# Generated by Django 4.0.4 on 2022-06-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maint_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='vehicle',
        ),
    ]
