# Generated by Django 4.0.4 on 2022-06-01 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maint_log', '0002_remove_maintenanceitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceitem',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date completed'),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='maint_log.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
