# Generated by Django 4.0.4 on 2022-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint_log', '0006_alter_maintenanceitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceitem',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date completed'),
        ),
    ]
