# Generated by Django 4.0.4 on 2022-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint_log', '0009_vehicle_maintenance_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='maintenance_intervals',
            field=models.TextField(default='Tire Rotation: 5,000 miles\n\nOil Change: 7,500 miles or every year\n\nCabin Air Filter Replace: 30,000 miles or every 2 years\n\nEngine Air Filter Replace: 30,000 miles or every 2 years\n\nTransmission Fluid Replace: 30,000 miles or every 2 years\n\nDifferential Fluid Replace: 30,000 miles or every 2 years\n\nBrake Fluid Replace: Every 3 years\n\nBattery Replace: Every 5 years\n\nEngine Coolant Replace: 60,000 or every 5 years\n\nSpark Plugs: 100,000 miles\n\nTiming Belt Replace: 100,000 miles', null=True),
        ),
    ]
